# Configuration for actions/labeler v5+
# https://github.com/actions/labeler

integration:
  - changed-files:
      - any-glob-to-any-file: "custom_components/**/*"

test:
  - changed-files:
      - any-glob-to-any-file: "tests/**/*"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

docs:
  - changed-files:
      - any-glob-to-any-file: 
          - "README.md"
          - "docs/**/*"
